# Generated by Django 2.2.4 on 2020-02-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookstore', models.CharField(max_length=20)),
                ('sale_qty', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('sale_date', models.DateTimeField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('sales', models.FloatField()),
                ('product', models.CharField(max_length=25)),
            ],
        ),
    ]
